name: Build package

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install build tools
        run: pip install build

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build package
        run: |
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyxdaq-dist
          path: dist
