name: Publish package to PyPI

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/run_tests.yml

  build:
    uses: ./.github/workflows/build_package.yml

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pyxdaq-dist
          path: dist

      - name: Extract version from pyproject.toml
        id: version
        run: |
          VERSION=$(sed -nE 's/^version *= *"(.*)"/\1/p' pyproject.toml)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: dist

  post_publish_test:
    needs: publish
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]
        py: ["3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install published package from PyPI
        run: |
          pip install pyxdaq==${{ needs.publish.outputs.version }}

      - name: Smoke test pyxdaq
        run: python -c "import pyxdaq; import pyxdaq.xdaq; print(pyxdaq.__version__)"
