name: Publish package to test PyPI

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_package.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pyxdaq-dist
          path: dist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: dist
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
