name: Test package

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os_arch:
          [
            { os: windows-2022, arch: x64 },
            { os: macos-15, arch: arm64 },
            { os: ubuntu-24.04, arch: x64 }
          ]
        py: ["3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os_arch.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tox
        run: pipx install tox

      - name: Run tox
        run: pipx run tox
